
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-miv-new
  namespace: 	miv   ## where prod is the name of the namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 3000Mi