apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-miv-new
  namespace: 	miv   ## where prod is the name of the namespace
spec:
  capacity:
    storage: 3000Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.28.59
    path: "/nfs/vol-miv-new/"